#! /bin/bash

GIT_VERSION=$(git -v | awk '{print $3}')

echo "My git version: $GIT_VERSION"

GTI_LATEST_VERSION=$(curl -s https://git-scm.com/download/win | grep -n  git | awk 'NR==2 {print $4}' |grep -oE 'v\d+\.\d+\.\d+' | tr -d v)

echo "Latest git version: $GTI_LATEST_VERSION"

if [ "$GIT_VERSION" == "$GTI_LATEST_VERSION" ]; then
    echo "Latest git version is installed already"
else
    echo "Latest git version in NOT installed"
    brew install git
fi
